USE [STEST]
GO

/****** Object:  View [wmwhse1].[CM_TDN_940]    Script Date: 2015/10/13 8:58:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE view [wmwhse1].[CM_TDN_940]
as
SELECT  [SITE],
		ORDERKEY,
		ORDERLINENUMBER,
		REQUESTORDER,
		REQUESTORDERLINE,
		CMPO,
		COMPONENTTYPE ,
		[STATUS],
		 CMSITE,
		 REQUESTEDSHIPDATE,
		  CMDUNS,
		  STORERKEY,
		  SKU,
		  SKUGROUP,
		  DESCR,
		  REMARK,
		  ASIC,
		  SUPPLIERDO,
		  SEAGATEPO,
		  COUNTRY,
		  PRIMEONLY,
		  case when ISNULL(NOOFFEEDER, '') = '' then '0' else NOOFFEEDER END AS   NOOFFEEDER,
		  REQLOC, 
		  replicate('0', 10 - len(CAST(SUM(QTY) as int))) + cast (CAST(SUM(QTY) as int) as varchar) as QTY
	 
from(
SELECT  'SZT' AS [SITE],
		T0.ORDERKEY,
		T5.ORDERLINENUMBER,
		T0.EXTERNORDERKEY as REQUESTORDER,
		T5.Susr2 as REQUESTORDERLINE,
		T0.EXTERNALORDERKEY2 AS CMPO,
		T3.SKUGROUP as COMPONENTTYPE ,
		T0.[STATUS],
		T0.CONSIGNEEKEY as CMSITE,
		T0.REQUESTEDSHIPDATE as REQUESTEDSHIPDATE,
		T4.DUNSID as CMDUNS,
	    T1.STORERKEY,
		T1.SKU,
		T3.SKUGROUP,
		T3.DESCR,
		T5.REMARK,
		T3.COMMODITYCLASS AS ASIC,
		T2.LOTTABLE02 AS SUPPLIERDO,
		T2.LOTTABLE03 AS SEAGATEPO,
		T2.LOTTABLE07 AS COUNTRY,
	    t5.PRIMEONLY AS PRIMEONLY,
		T5.SUsr1 AS NOOFFEEDER,
		T5.REQLOC, 
		T1.QTY
 FROM [WMWHSE1].[ORDERS] T0 ,
      [WMWHSE1].[ORDERDETAIL] T5,
	  [WMWHSE1].[PICKDETAIL] T1,
      [WMWHSE1].[LOTATTRIBUTE] T2,
      [WMWHSE1].[SKU] T3,
	  [WMWHSE1].[STORER] T4 
WHERE   T1.LOT = T2.LOT AND
		t5.ORDERKEY = t1.ORDERKEY And
		t5.ORDERLINENUMBER = t1.ORDERLINENUMBER and
		T0.ORDERKEY = T5.ORDERKEY AND
		T0.ORDERKEY= T1.ORDERKEY  AND 
		T3.STORERKEY = t5.STORERKEY AND
		T3.STORERKEY = t1.STORERKEY AND
		T1.SKU = T3.SKU AND	 
	    T0.CONSIGNEEKEY = T4.STORERKEY AND 
		T4.[TYPE]=N'2' AND
		T0.[TYPE] IN ( N'0',N'15',N'10')
		) g
		GROUP BY 
		[SITE],
		ORDERKEY,
		ORDERLINENUMBER,
		REQUESTORDER,
		REQUESTORDERLINE,
		CMPO,
		COMPONENTTYPE ,
		[STATUS],
		 CMSITE,
		 REQUESTEDSHIPDATE,
		  CMDUNS,
		  STORERKEY,
		  SKU,
		  SKUGROUP,
		  DESCR,
		  REMARK,
		  ASIC,
		  SUPPLIERDO,
		  SEAGATEPO,
		  COUNTRY,
		  PRIMEONLY,
		  NOOFFEEDER,
		  REQLOC

GO


