USE [STEST]
GO

/****** Object:  View [wmwhse1].[ORDER_POD]    Script Date: 2015/10/13 8:59:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE view [wmwhse1].[ORDER_POD]
as
SELECT T0.ORDERKEY,T0.EXTERNORDERKEY,T3.SKUGROUP COMCODE ,T0.[STATUS],T0.CONSIGNEEKEY ,T0.ACTUALSHIPDATE as TRANSACTIONDATE,
 T4.DUNSID as CMDUNS,
 T1.STORERKEY,T1.SKU,T3.SKUGROUP,T3.COMMODITYCLASS ,T1.QTY,T2.LOTTABLE01
,T2.LOTTABLE02,T2.LOTTABLE03,T2.LOTTABLE04,T2.LOTTABLE05
,T2.LOTTABLE06,T2.LOTTABLE07,T2.LOTTABLE08,T2.LOTTABLE09
,T2.LOTTABLE10
 FROM [WMWHSE1].[ORDERS] T0 ,
	  [WMWHSE1].[PICKDETAIL] T1,
      [WMWHSE1].[LOTATTRIBUTE] T2,
      [WMWHSE1].[SKU] T3,
	  [WMWHSE1].[STORER] T4 
WHERE   T1.LOT = T2.LOT AND
		T0.ORDERKEY= T1.ORDERKEY  AND 
		T1.STORERKEY = T3.STORERKEY and
		T1.SKU = T3.SKU AND	 
	    T0.CONSIGNEEKEY = T4.STORERKEY AND 
		T4.[TYPE]=N'2'AND
		T3.COMMODITYCLASS =N'NON ASIC' AND
		T0.[TYPE] IN ( N'0',N'15',N'10')





GO


