//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApp.SAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SAP.ZFI_CREATE_AR_FOR_WMS")]
    public interface ZFI_CREATE_AR_FOR_WMS {
        
        // CODEGEN: Parameter 'ArData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TestConsoleApp.SAP.ZfiCreateArForWmsResponse ZfiCreateArForWms(TestConsoleApp.SAP.ZfiCreateArForWmsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiWmsStru : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerNoField;
        
        private decimal amountValueField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CustomerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
                this.RaisePropertyChanged("CustomerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal AmountValue {
            get {
                return this.amountValueField;
            }
            set {
                this.amountValueField = value;
                this.RaisePropertyChanged("AmountValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmesMsgStru : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZfiCreateArForWms", WrapperNamespace="urn:sap-com:document:sap:soap:functions:mc-style", IsWrapped=true)]
    public partial class ZfiCreateArForWmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZfiWmsStru[] ArData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmesMsgStru[] MsgTab;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WmsBatchid;
        
        public ZfiCreateArForWmsRequest() {
        }
        
        public ZfiCreateArForWmsRequest(ZfiWmsStru[] ArData, ZmesMsgStru[] MsgTab, string PostingDate, string WmsBatchid) {
            this.ArData = ArData;
            this.MsgTab = MsgTab;
            this.PostingDate = PostingDate;
            this.WmsBatchid = WmsBatchid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZfiCreateArForWmsResponse", WrapperNamespace="urn:sap-com:document:sap:soap:functions:mc-style", IsWrapped=true)]
    public partial class ZfiCreateArForWmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZfiWmsStru[] ArData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentYear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmesMsgStru[] MsgTab;
        
        public ZfiCreateArForWmsResponse() {
        }
        
        public ZfiCreateArForWmsResponse(ZfiWmsStru[] ArData, string CompanyCode, string DocumentNumber, string DocumentYear, ZmesMsgStru[] MsgTab) {
            this.ArData = ArData;
            this.CompanyCode = CompanyCode;
            this.DocumentNumber = DocumentNumber;
            this.DocumentYear = DocumentYear;
            this.MsgTab = MsgTab;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ZFI_CREATE_AR_FOR_WMSChannel : TestConsoleApp.SAP.ZFI_CREATE_AR_FOR_WMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ZFI_CREATE_AR_FOR_WMSClient : System.ServiceModel.ClientBase<TestConsoleApp.SAP.ZFI_CREATE_AR_FOR_WMS>, TestConsoleApp.SAP.ZFI_CREATE_AR_FOR_WMS {
        
        public ZFI_CREATE_AR_FOR_WMSClient() {
        }
        
        public ZFI_CREATE_AR_FOR_WMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZFI_CREATE_AR_FOR_WMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFI_CREATE_AR_FOR_WMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFI_CREATE_AR_FOR_WMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestConsoleApp.SAP.ZfiCreateArForWmsResponse TestConsoleApp.SAP.ZFI_CREATE_AR_FOR_WMS.ZfiCreateArForWms(TestConsoleApp.SAP.ZfiCreateArForWmsRequest request) {
            return base.Channel.ZfiCreateArForWms(request);
        }
        
        public string ZfiCreateArForWms(ref ZfiWmsStru[] ArData, ref ZmesMsgStru[] MsgTab, string PostingDate, string WmsBatchid, out string DocumentNumber, out string DocumentYear) {
            TestConsoleApp.SAP.ZfiCreateArForWmsRequest inValue = new TestConsoleApp.SAP.ZfiCreateArForWmsRequest();
            inValue.ArData = ArData;
            inValue.MsgTab = MsgTab;
            inValue.PostingDate = PostingDate;
            inValue.WmsBatchid = WmsBatchid;
            TestConsoleApp.SAP.ZfiCreateArForWmsResponse retVal = ((TestConsoleApp.SAP.ZFI_CREATE_AR_FOR_WMS)(this)).ZfiCreateArForWms(inValue);
            ArData = retVal.ArData;
            DocumentNumber = retVal.DocumentNumber;
            DocumentYear = retVal.DocumentYear;
            MsgTab = retVal.MsgTab;
            return retVal.CompanyCode;
        }
    }
}
