//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCodePrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarCodePrinter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--Type:KAIFA_3PL_1 DO={3}--&gt;
        ///&lt;!DOCTYPE labels SYSTEM &quot;..\..\Batch\label.dtd&quot;&gt;
        ///&lt;labels _FORMAT=&quot;KAIFA_3PL_1&quot; _PRINTERNAME=&quot;{0}&quot; _QUANTITY=&quot;{1}&quot;&gt;
        ///	&lt;label&gt;
        ///		&lt;variable name=&quot;PO&quot;&gt;{2}&lt;/variable&gt;
        ///		&lt;variable name=&quot;DO&quot;&gt;{3}&lt;/variable&gt;
        ///		&lt;variable name=&quot;PN&quot;&gt;{4}&lt;/variable&gt;
        ///		&lt;variable name=&quot;QTY&quot;&gt;{5}&lt;/variable&gt;
        ///		&lt;variable name=&quot;TRACE&quot;&gt;{6}&lt;/variable&gt;
        ///		&lt;variable name=&quot;GTS&quot;&gt;{7}&lt;/variable&gt;
        ///                                     &lt;variable name=&quot;COO&quot;&gt;{8}&lt;/v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kf3pl {
            get {
                return ResourceManager.GetString("kf3pl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rugged_climbing1 {
            get {
                object obj = ResourceManager.GetObject("rugged_climbing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--Type:KAIFA_STX_1 TRACE={7}--&gt;
        ///&lt;!DOCTYPE labels SYSTEM &quot;..\..\Batch\label.dtd&quot;&gt;
        ///&lt;labels _FORMAT=&quot;KAIFA_STX_1&quot; _PRINTERNAME=&quot;{0}&quot; _QUANTITY=&quot;{1}&quot;&gt;
        ///	&lt;label&gt;
        ///		&lt;variable name=&quot;PART&quot;&gt;{2}&lt;/variable&gt;
        ///		&lt;variable name=&quot;QTY&quot;&gt;{3}&lt;/variable&gt;
        ///		&lt;variable name=&quot;LOT&quot;&gt;{4}&lt;/variable&gt;
        ///		&lt;variable name=&quot;ASL&quot;&gt;{5}&lt;/variable&gt;
        ///		&lt;variable name=&quot;VEN&quot;&gt;{6}&lt;/variable&gt;
        ///		&lt;variable name=&quot;TRACE&quot;&gt;{7}&lt;/variable&gt;
        ///		&lt;variable name=&quot;DCODE&quot;&gt;{8}&lt;/variable&gt;
        ///	&lt;/label&gt;
        ///&lt;/lab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stxpl {
            get {
                return ResourceManager.GetString("stxpl", resourceCulture);
            }
        }
    }
}
